### ISSUE TITLE
Test Error Windows (RegistryInstallerListener)

### ISSUE THREAD

**Issue by Sailsman63** [izpack/izpack#361]
Running `mvn verify` on windows 7 pro, the following test error occurs:

>Test set: com.izforge.izpack.event.RegistryInstallerListenerTest

>Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.078 sec <<< FAILURE!
>testRegistry(com.izforge.izpack.event.RegistryInstallerListenerTest)  Time elapsed: 0 sec  <<< ERROR!
>com.izforge.izpack.api.exception.NativeLibException
	at com.izforge.izpack.util.os.Win_RegistryHandler.getRegistry(Win_RegistryHandler.java:385)
	at com.izforge.izpack.util.os.Win_RegistryHandler.setRoot(Win_RegistryHandler.java:277)
	at com.izforge.izpack.event.RegistryInstallerListenerTest.deleteKey(RegistryInstallerListenerTest.java:352)
	at com.izforge.izpack.event.RegistryInstallerListenerTest.testRegistry(RegistryInstallerListenerTest.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)

This test requires to be run as Admin user. When run as Admin, the error occurs.

**Comment by akuhtz** [comment]
The same problem occurs on my box. 
In AbstractParser:indexOfOperator() is a detection of the terminating quote sign but in the case shown below in *Description* the logic fails.

```
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\hcmon]
"Type"=dword:00000001
"Start"=dword:00000002
"ErrorControl"=dword:00000001
"ImagePath"=hex(2):5c,00,3f,00,3f,00,5c,00,43,00,3a,00,5c,00,57,00,69,00,6e,00,\
  64,00,6f,00,77,00,73,00,5c,00,73,00,79,00,73,00,74,00,65,00,6d,00,33,00,32,\
  00,5c,00,64,00,72,00,69,00,76,00,65,00,72,00,73,00,5c,00,68,00,63,00,6d,00,\
  6f,00,6e,00,2e,00,73,00,79,00,73,00,00,00
"DisplayName"="VMware hcmon"
"Group"="Extended base"
"Description"="VMware USB Driver.

"
```

**Comment by Sailsman63** [comment]
Sorry, @akuhtz as far as I can tell, this commit does not fix the issue for me. Running the tests replicates the exact same issue, only difference in the test output is the time.

**Comment by akuhtz** [comment]
@Sailsman63 Thanks for testing.
Tested again on another box where it fails, too. Never reached this step until now :-)

Now it fails while parsing the last line.
```
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\UmPass\Enum]
"Count"=dword:00000001
"NextInstance"=dword:00000001
"0"="uuid:12345678-0000-0000-0000-00000000abcd\\UMB\\3&44ecbc&0&uuid:12345678-0000-0000-0000-00000000abcd"
```
The issue is, that *uuid* is not know as type in the class Registry and this causes the NPE. Will try to fix that.

**Comment by Sailsman63** [comment]
Umm... still no. How could I go about getting you a copy of whatever line on my system that is not being parsed correctly? I'm a self-taught recreational developer, but I'm willing to learn my way around something new.

**Comment by akuhtz** [comment]
I've added a System.out.println(line); in \izpack\izpack-util\src\main\java\com\izforge\izpack\util\config\base\spi\AbstractParser at the begin of ```parseOptionLine```.

The part of the windows registry is exported to your temp directory and parsed with the IniParser IIRC.

Could you paste the exception?
Currently I get this one at the end of my ```com.izforge.izpack.event.RegistryInstallerListenerTest.txt```:
```
Caused by: java.lang.UnsatisfiedLinkError: Failed to load library: COIOSHelper
	at com.izforge.izpack.util.Librarian.loadLibrary(Librarian.java:133)
	at com.coi.tools.os.izpack.COIOSHelper.addDependant(COIOSHelper.java:102)
```
and I thought it's because I haven't built the native libs.

**Comment by rkrell** [comment]
@akuhtz: Just a note:  com\izforge\izpack\util\config\base\spi\AbstractParser has nothing in common with COIOSHelper. CoiosHelper is the legacy way of IzPack accessing the Windows registry using a precompiled DLL you have to declare in install.xml (there is already a built-in binary available with the IzPack sources). com\izforge\izpack\util\config\ uses a new way accessing the registry by executing standard Windows commands like on the command line. RegistryInstallerListener in fact still uses the CoiosHelper way, although I intended to migrate it to the com\izforge\izpack\util\config\, too, to avoid precompiled native binaries and JNI in this case. This is still to do in future.

**Comment by Sailsman63** [comment]
In that case, perhaps the best response to this issue is to put it off until the migration is complete? Or, if one really wants to work on this, to make a start on the migration...

**Comment by rkrell** [comment]
Not necessarily. If there is an easy solution with COIOSHelper it will be ok. No pressure about migrating RegistryInstallerListener.

**Comment by akuhtz** [comment]
@Sailsman63 Just commited the next fix. Now the build of izpack passes on my windows-box. Will test tonight at home on my other windows-box. Please test on your box, thank you.

**Comment by Sailsman63** [comment]
Now, that commit passes. Build Success all around. Thanks.

**Comment by akuhtz** [comment]
Thanks for testing. Build passes on my windows-box at home, too.
