### ISSUE TITLE
Is there a way to detect Automated install?

### ISSUE THREAD

**Issue by yukron** [izpack/izpack#365]
Since user input validators do not work in unattended mode, I've added Panel validator, which is triggered after specific Panel switch. 
The problem is that in GUI/console mode both validators are invoked, while unattended install only uses Panel validator.

So I am trying to get some sort of flag when automated installation is triggered, which can be passed to condition as variable and later be used in validator class="some class" conditionid="automated" tag.

I have not found any traces of such flag in sources, but think that this line can be added:
https://github.com/yukron/izpack/commit/9ca9cdd4583b201028f5db642db61cb99f38f043

**Comment by rkrell** [comment]
This is not necessary. There is a static public method
```java
com.izforge.izpack.installer.bootstrap.Installer.getInstallerMode()
```
available. Just pick the correct value to compare:
```java
Installer.getInstallerMode() == Installer.INSTALLER_AUTO
```

**Comment by yukron** [comment]
Running in Windows:
```bash
java -jar myInstaller.jar -options C:\some.properties
```

Installer.getInstallerMode() returns 2 (INSTALLER_CONSOLE), while Installer.INSTALLER_AUTO equals 1.

Omitting -options c:\some.properties makes Installer.getInstallerMode() returns 0 (INSTALLER_GUI).

**Comment by yukron** [comment]
OK, I think I got it: 'real' automated instllations only works with some-file.xml input, not *.properties files. Which means that unattended installations triggered by -options file.properties are being proccesed by launchConsoleInstaller and in fact are 'fake' automated installations.

Looks like I need another way of detecting if -options argument was called so I can set my conditions.

**Comment by rkrell** [comment]
Yes, the - options mode is different.
Currently, the AUTO_MODE is really set just if you use an auto-install xml record file as parameter.
Could be probably improved, not sure at the moment.
Not for 5.0, there should come in just major bugs to release it soon.

But we can file a change for 5.0.X bug fix releases or 5.1.

**Comment by yukron** [comment]
I think this can be added to resolve my issue:
https://github.com/yukron/izpack/commit/611916a3154a9393eb48baef00efb01c13f7bca4
Just allowing to get current consoleAction (in my case it is 2 or CONSOLE_FROM_TEMPLATE, which corresponds to -options argument), so we can do the following compare:

```Java
// Let's skip Panel validation in case no there is no -options argument.
if (Installer.getConsoleMode() != Installer.CONSOLE_FROM_TEMPLATE) {
    return Status.OK;
}
```
Should do a pull-request?

**Comment by rkrell** [comment]
You can send pull requests whenever you want.
Unfortunately I cannot review this immediately, maybe someone else can.

In each case this is an API change, should not go to 5.0.0 release in case it will be reviewed successfully, but to a later one (probably 5.0.1 or 5.1).

**Comment by yukron** [comment]
Ok, thanks.
