### ISSUE TITLE
Pass -options some.properties file props to installer?

### ISSUE THREAD

**Issue by yukron** [izpack/izpack#391]
Is it possible to push properties from "some.properties" file somewhere to installData so installer would know new variables?

So basically I need to generate new key=value pair (or some new Properites object I can operate with) from "some.properties" so my installer will know new variables and use them.

**Comment by maztan** [comment]
Is this what you are taking about: https://izpack.atlassian.net/wiki/display/IZPACK/Variables

**Comment by rkrell** [comment]
It is. See https://izpack.atlassian.net/wiki/display/IZPACK/Dynamic+Variables, section *Values from Property/Option Files*.

BTW, please pass such questions to the izpack-user mailing list, see http://news.izpack.org/2015/06/relocation-of-izpack-services-after.html. It is a better place for all than creating Github issues from that. Thank you.

**Comment by yukron** [comment]
> Is this what you are taking about: https://izpack.atlassian.net/wiki/display/IZPACK/Variables
No, it is not. I need to supply key=value pairs to already built installer.

Anyway, I've figured it out: changed 1 line in izapck-installer-api, will post pull-request with it.
