### ISSUE TITLE
Pack-Specific-Variables

### ISSUE THREAD

**Issue by oers** [izpack/izpack#393]
This is a feature request (I didn't find anything like this in the documentation)

I would like to copy and parse a specific file.
This file has a variable like %SERVER_NAME%.
This Variable is different for each pack.

I want to avoid copying this file with ant or something else beforehand.

So I would like to be able to declare something like
```xml
<variables>
 ..
</variables> 
``` 

but in the pack section.

**Comment by rkrell** [comment]
This seems to be covered by the current features.

Use [<dynamicvariables>](https://izpack.atlassian.net/wiki/display/IZPACK/Dynamic+Variables) along with the predefined [izpack.selected.<packname>](https://izpack.atlassian.net/wiki/display/IZPACK/Predefined+Conditions) conditions or define your own conditions using the [packselection condition](https://izpack.atlassian.net/wiki/display/IZPACK/Packselection+Condition).
See:
- https://izpack.atlassian.net/wiki/display/IZPACK/Dynamic+Variables (including the examples there)
- https://izpack.atlassian.net/wiki/display/IZPACK/Predefined+Conditions
- https://izpack.atlassian.net/wiki/display/IZPACK/Packselection+Condition

Example:

```xml
<dynamicvariables>
    <variable name="SERVER_NAME" value="" condition="izpack.selected.My Pack 1" />
    <variable name="SERVER_NAME" value="" condition="izpack.selected.My Pack 2" />
</dynamicvariables>
```

```xml
<conditions>
  <condition type="packselection" id="myPack1Selected">
    <name>My Pack 1</name>
  </condition>
  <condition type="packselection" id="myPack2Selected">
    <name>My Pack 2</name>
  </condition>
</conditions>

<dynamicvariables>
    <variable name="SERVER_NAME" value="" condition="myPack1Selected" />
    <variable name="SERVER_NAME" value="" condition="myPack2Selected" />
</dynamicvariables>
```

**Comment by rkrell** [comment]
For technical questions there should be better used the mailing list izpack-user at Google Groups, see http://news.izpack.org/2015/06/relocation-of-izpack-services-after.html about how to subscribe.

After discussions here we can decide whether to really raise a feature request or whatever.

Thank you.
